# Cargo.toml file for rust projects
[package]
name = "ecc"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]

name="testcurve"
path="src/testcurve.rs"

[[bin]]
name="EC256"
path="src/EC256.rs"

[[bin]]
name="Ed448"
path="src/Ed448.rs"

[features]

